#ifndef CONSTANTS_H
#define CONSTANTS_H

#define GENOME_ALLELE_NUM 16
#define MAX_FOOD 1000.0f
#define FOOD_BASE_CONSUMPTION 1.0f
#define MAX_SIZE 100
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#endif